### ISSUE TITLE
Order of suggested items

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#43]
See:

![ashampoo_snap_2016 08 13_16h02m45s_001_](https://cloud.githubusercontent.com/assets/17312717/17643619/c243b414-616f-11e6-8836-3c24765b83d0.png)

**Comment by rrezino** [comment]
It should be working, maybe I broke something! I'll take a look!

**Comment by rrezino** [comment]
hun..... I've just looked to the situation.  How do you think it should be ? 
Because currently it work like:
1) the list is ordered by ascending strings
2) the item most likely to be right is selected
As you can see on you example. Things are organized by string, to make easier you to find what you want, but System.SysUtils.TFilename is already selected, so is just click enter.

**Comment by jaclas** [comment]
It's not true. See, I select TFileName and press ctrl+shift+a:
![ashampoo_snap_2016 08 17_11h37m31s_001_](https://cloud.githubusercontent.com/assets/17312717/17731888/aaeb4c5c-646f-11e6-99b1-acd9f5d6346d.png)

**Comment by jaclas** [comment]
Imho each string should be given weight. The list should be sorted according to this weight.
The weight should be calculated, eg. from:
- completeness of expression (including all characters)
- the accuracy of uppercase letters (FileName -> occurrence capital letters F and N)
- the location in project units (higher weight)
- the location in RTL library (high weight)
- location in external libraries (average weight)
- etc.

**Comment by jaclas** [comment]
I forgot...
Sorting because this is how works the Code Insight - and for that we are accustomed :-)

**Comment by rrezino** [comment]
I commit a test version, if u'd like to try

**Comment by jaclas** [comment]
It is better, but far from perfect ;-)
See this example:

![ashampoo_snap_2016 08 26_17h48m34s_002_](https://cloud.githubusercontent.com/assets/17312717/18011454/98a064fe-6bb5-11e6-877b-9a621835e235.png)

**Comment by jaclas** [comment]
Next example:
![ashampoo_snap_2016 09 05_13h33m57s_002_](https://cloud.githubusercontent.com/assets/17312717/18246803/5b652320-736e-11e6-8fb2-fcefdecfe4d1.png)

**Comment by rfrezino** [comment]
Jaclas, by now, I don't change the order of the item on the list.
It's organized by alphabetical order, because, if I organize it by other thing, if I dont show you the right line and you need to search for the item, and you will be completly lost, because you will not have any visible logic to search for the item. 
What I do is pre-select the most possible item. (blue line).

I don't know if in this case you clicked on the item, but the idea is when you open the screen, items will be organized by char, but I will select the most possible item.

**Comment by jaclas** [comment]
Next example :-)

![ashampoo_snap_2016 09 27_11h37m25s_002_](https://cloud.githubusercontent.com/assets/17312717/18868074/27940238-84a7-11e6-93e8-88b8cee6f731.png)

**Comment by jaclas** [comment]
![ashampoo_snap_2016 10 05_15h53m47s_001_](https://cloud.githubusercontent.com/assets/17312717/19115998/4112c514-8b14-11e6-8f6f-ee645340f3fe.png)

**Comment by jaclas** [comment]
next example :-)

![ashampoo_snap_2016 10 14_15h36m53s_001_](https://cloud.githubusercontent.com/assets/17312717/19389436/542d8a1e-9224-11e6-9755-e6128a06f212.png)

ps. thx for configuration window 👍

**Comment by jaclas** [comment]
Next example of incorrect match:

![ashampoo_snap_2016 12 20_16h26m02s_001_](https://cloud.githubusercontent.com/assets/17312717/21356284/5ce05754-c6d1-11e6-8a03-9f6cf24e2687.png)

**Comment by jaclas** [comment]
![ashampoo_snap_2016 12 30_09h58m22s_001_](https://cloud.githubusercontent.com/assets/17312717/21562168/ca5215aa-ce76-11e6-9934-6fa522fb3515.png)

**Comment by rrezino** [comment]
I did some improvments now, but what appears first, default or installed things like this it will be necessary to build something to configure it. I will not get into it now
